######### Registro dos dados
POST http://127.0.0.1:3333/partituras HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mw.aPvJLwqjcj5GPSErhnILQFsUZaty6c1nQVGDW0F6D_swDAyBQHXttjdLE1Wp

{
    "title": "Hallellujah",
    "autor": "Leonard Cohen",
    "ano": "1984"
}