######### Registro dos dados
POST http://127.0.0.1:3333/partituras HTTP/1.1
Content-Type: application/json
Authorization: Bearer NQ.OhEtsQjgK5HQrZ-EWDVr-uqtc3HUrNl8lAk0De3o5vQ7NokQSZOsOSPZMGph

{
    "title": " ",
    "autor": " ",
    "ano": " "
}